class XsltEngine {
  constructor(mod) {
    this.mod = mod;
    this._transform = mod.cwrap(
      "xsltJsTransform",
      "number",
      ["number", "number"],
      { async: true }
    );
  }

  async transform(xsltFile, xml) {
    if (!xsltFile) {
      throw "Empty XSLT file name";
    }

    if (!xml) {
      throw "Empty XML String";
    }

    const xsltPtr = this.mod.allocateUTF8(xsltFile);
    const xmlPtr = this.mod.allocateUTF8(xml);

    try {
      const outputPtr = await this._transform(xsltPtr, xmlPtr);
      if (outputPtr === 0) {
        const errPtr = this.mod._xsltJsLastError();
        if (errPtr === 0) {
          return "";
        }

        const err = this.mod.UTF8ToString(errPtr);
        throw "Transformation failed: " + err;
      }

      const output = this.mod.UTF8ToString(outputPtr);
      this.mod._free(outputPtr);
      return output;
    } finally {
      this.mod._free(xsltPtr);
      this.mod._free(xmlPtr);
    }
  }
}

var createXsltEngine = (() => {

var createXsltModule = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(createXsltModule) {
  createXsltModule = createXsltModule || {};


var g;g||(g=typeof createXsltModule !== 'undefined' ? createXsltModule : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var da={},h;for(h in g)g.hasOwnProperty(h)&&(da[h]=g[h]);var ea="./this.program";function fa(a,b){throw b;}var l="";"undefined"!==typeof document&&document.currentScript&&(l=document.currentScript.src);_scriptDir&&(l=_scriptDir);0!==l.indexOf("blob:")?l=l.substr(0,l.lastIndexOf("/")+1):l="";var ha=g.print||console.log.bind(console),p=g.printErr||console.warn.bind(console);
for(h in da)da.hasOwnProperty(h)&&(g[h]=da[h]);da=null;g.thisProgram&&(ea=g.thisProgram);g.quit&&(fa=g.quit);var ia;g.wasmBinary&&(ia=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&r("no native wasm support detected");var ja,v=!1;function w(a,b){a||r("Assertion failed: "+b)}function ka(a){var b=g["_"+a];w(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function la(a,b,c,d,e){function f(t){return"string"===b?y(t):"boolean"===b?!!t:t}var k={string:function(t){var z=0;if(null!==t&&void 0!==t&&0!==t){var D=(t.length<<2)+1;z=ma(D);na(t,B,z,D)}return z},array:function(t){var z=ma(t.length);E.set(t,z);return z}};a=ka(a);var m=[],n=0;if(d)for(var q=0;q<d.length;q++){var u=k[c[q]];u?(0===n&&(n=oa()),m[q]=u(d[q])):m[q]=d[q]}c=a.apply(null,m);d="object"===typeof pa&&0<qa.length;if("object"===typeof pa&&F&&!d)return new Promise(function(t){qa.push(function(z){0!==
n&&ra(n);t(f(z))})});c=f(c);0!==n&&ra(n);return e&&e.async?Promise.resolve(c):c}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?ta(B,a,b):""}
function na(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var m=a.charCodeAt(++f);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function va(a){var b=ua(a)+1,c=G(b);c&&na(a,E,c,b);return c}var wa,E,B,H,xa,I;
function ya(){var a=ja.buffer;wa=a;g.HEAP8=E=new Int8Array(a);g.HEAP16=H=new Int16Array(a);g.HEAP32=I=new Int32Array(a);g.HEAPU8=B=new Uint8Array(a);g.HEAPU16=xa=new Uint16Array(a);g.HEAPU32=new Uint32Array(a);g.HEAPF32=new Float32Array(a);g.HEAPF64=new Float64Array(a)}var za=[],Aa=[],Da=[];function Ea(){var a=g.preRun.shift();za.unshift(a)}var J=0,Fa=null,Ga=null;g.preloadedImages={};g.preloadedAudios={};
function r(a){if(g.onAbort)g.onAbort(a);p(a);v=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ha(){return K.startsWith("data:application/octet-stream;base64,")}var K;K="xslt.wasm";if(!Ha()){var Ia=K;K=g.locateFile?g.locateFile(Ia,l):l+Ia}function Ja(){var a=K;try{if(a==K&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}catch(b){r(b)}}
function Ka(){return ia||"function"!==typeof fetch?Promise.resolve().then(function(){return Ja()}):fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ja()})}var L,M;function La(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Wa;"number"===typeof c?void 0===b.Ha?dynCall_v.call(null,c):Ma.apply(null,[c,b.Ha]):c(void 0===b.Ha?null:b.Ha)}}}
function Na(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function N(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Na(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Oa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Pa(a){if("/"===a)return"/";a=N(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Qa(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){r("randomDevice")}}
function Ra(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Na(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Sa=[];function Ta(a,b){Sa[a]={input:[],da:[],pa:b};Ua(a,Va)}
var Va={open:function(a){var b=Sa[a.node.wa];if(!b)throw new O(43);a.ba=b;a.seekable=!1},close:function(a){a.ba.pa.flush(a.ba)},flush:function(a){a.ba.pa.flush(a.ba)},read:function(a,b,c,d){if(!a.ba||!a.ba.pa.Xa)throw new O(60);for(var e=0,f=0;f<d;f++){try{var k=a.ba.pa.Xa(a.ba)}catch(m){throw new O(29);}if(void 0===k&&0===e)throw new O(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.ba||!a.ba.pa.Ma)throw new O(60);try{for(var e=
0;e<d;e++)a.ba.pa.Ma(a.ba,b[c+e])}catch(f){throw new O(29);}d&&(a.node.timestamp=Date.now());return e}},Wa={Xa:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;var c=Array(ua(b)+1);b=na(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Ma:function(a,b){null===b||10===b?(ha(ta(a.da,0)),a.da=[]):0!=b&&a.da.push(b)},
flush:function(a){a.da&&0<a.da.length&&(ha(ta(a.da,0)),a.da=[])}},Xa={Ma:function(a,b){null===b||10===b?(p(ta(a.da,0)),a.da=[]):0!=b&&a.da.push(b)},flush:function(a){a.da&&0<a.da.length&&(p(ta(a.da,0)),a.da=[])}},P={ja:null,ia:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.ja||(P.ja={dir:{node:{ha:P.Y.ha,la:P.Y.la,ua:P.Y.ua,Ca:P.Y.Ca,fb:P.Y.fb,ib:P.Y.ib,gb:P.Y.gb,bb:P.Y.bb,Fa:P.Y.Fa},stream:{oa:P.W.oa}},file:{node:{ha:P.Y.ha,
la:P.Y.la},stream:{oa:P.W.oa,read:P.W.read,write:P.W.write,Ra:P.W.Ra,Za:P.W.Za,ab:P.W.ab}},link:{node:{ha:P.Y.ha,la:P.Y.la,xa:P.Y.xa},stream:{}},Sa:{node:{ha:P.Y.ha,la:P.Y.la},stream:Ya}});c=Za(a,b,c,d);16384===(c.mode&61440)?(c.Y=P.ja.dir.node,c.W=P.ja.dir.stream,c.Z={}):32768===(c.mode&61440)?(c.Y=P.ja.file.node,c.W=P.ja.file.stream,c.aa=0,c.Z=null):40960===(c.mode&61440)?(c.Y=P.ja.link.node,c.W=P.ja.link.stream):8192===(c.mode&61440)&&(c.Y=P.ja.Sa.node,c.W=P.ja.Sa.stream);c.timestamp=Date.now();
a&&(a.Z[b]=c,a.timestamp=c.timestamp);return c},Ab:function(a){return a.Z?a.Z.subarray?a.Z.subarray(0,a.aa):new Uint8Array(a.Z):new Uint8Array(0)},Ua:function(a,b){var c=a.Z?a.Z.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Z,a.Z=new Uint8Array(b),0<a.aa&&a.Z.set(c.subarray(0,a.aa),0))},wb:function(a,b){if(a.aa!=b)if(0==b)a.Z=null,a.aa=0;else{var c=a.Z;a.Z=new Uint8Array(b);c&&a.Z.set(c.subarray(0,Math.min(b,a.aa)));a.aa=b}},Y:{ha:function(a){var b={};b.ob=
8192===(a.mode&61440)?a.id:1;b.Ka=a.id;b.mode=a.mode;b.vb=1;b.uid=0;b.qb=0;b.wa=a.wa;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.aa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.jb=new Date(a.timestamp);b.tb=new Date(a.timestamp);b.nb=new Date(a.timestamp);b.kb=4096;b.lb=Math.ceil(b.size/b.kb);return b},la:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.wb(a,b.size)},ua:function(){throw $a[44];},Ca:function(a,
b,c,d){return P.createNode(a,b,c,d)},fb:function(a,b,c){if(16384===(a.mode&61440)){try{var d=ab(b,c)}catch(f){}if(d)for(var e in d.Z)throw new O(55);}delete a.parent.Z[a.name];a.parent.timestamp=Date.now();a.name=c;b.Z[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},ib:function(a,b){delete a.Z[b];a.timestamp=Date.now()},gb:function(a,b){var c=ab(a,b),d;for(d in c.Z)throw new O(55);delete a.Z[b];a.timestamp=Date.now()},bb:function(a){var b=[".",".."],c;for(c in a.Z)a.Z.hasOwnProperty(c)&&b.push(c);
return b},Fa:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},xa:function(a){if(40960!==(a.mode&61440))throw new O(28);return a.link}},W:{read:function(a,b,c,d,e){var f=a.node.Z;if(e>=a.node.aa)return 0;a=Math.min(a.node.aa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===E.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Z||a.Z.subarray)){if(f)return a.Z=b.subarray(c,
c+d),a.aa=d;if(0===a.aa&&0===e)return a.Z=b.slice(c,c+d),a.aa=d;if(e+d<=a.aa)return a.Z.set(b.subarray(c,c+d),e),d}P.Ua(a,e+d);if(a.Z.subarray&&b.subarray)a.Z.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Z[e+f]=b[c+f];a.aa=Math.max(a.aa,e+d);return d},oa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.aa);if(0>b)throw new O(28);return b},Ra:function(a,b,c){P.Ua(a.node,b+c);a.node.aa=Math.max(a.node.aa,b+c)},Za:function(a,b,c,d,e,f){if(0!==b)throw new O(28);if(32768!==
(a.node.mode&61440))throw new O(43);a=a.node.Z;if(f&2||a.buffer!==wa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;r();c=void 0;if(!c)throw new O(48);E.set(a,c)}else d=!1,c=a.byteOffset;return{Db:c,zb:d}},ab:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new O(43);if(e&2)return 0;P.W.write(a,b,0,d,c,!1);return 0}}},bb=null,cb={},Q=[],db=1,eb=null,gb=!0,hb={},O=null,$a={};
function R(a,b){a=Ra("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Va:!0,Na:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Na)throw new O(32);a=Na(a.split("/").filter(function(k){return!!k}),!1);var e=bb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=ab(e,a[d]);c=N(c+"/"+a[d]);e.Da&&(!f||f&&b.Va)&&(e=e.Da.root);if(!f||b.Ia)for(f=0;40960===(e.mode&61440);)if(e=ib(c),c=Ra(Oa(c),e),e=R(c,{Na:b.Na}).node,40<f++)throw new O(32);}return{path:c,node:e}}
function jb(a){for(var b;;){if(a===a.parent)return a=a.ia.$a,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function kb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%eb.length}function ab(a,b){var c;if(c=(c=lb(a,"x"))?c:a.Y.ua?0:2)throw new O(c,a);for(c=eb[kb(a.id,b)];c;c=c.ub){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Y.ua(a,b)}function Za(a,b,c,d){a=new mb(a,b,c,d);b=kb(a.parent.id,a.name);a.ub=eb[b];return eb[b]=a}
var nb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function ob(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function lb(a,b){if(gb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function pb(a,b){try{return ab(a,b),20}catch(c){}return lb(a,"wx")}function qb(a,b){b=b||4096;for(a=a||0;a<=b;a++)if(!Q[a])return a;throw new O(33);}
function rb(a,b,c){sb||(sb=function(){},sb.prototype={});var d=new sb,e;for(e in a)d[e]=a[e];a=d;b=qb(b,c);a.ea=b;return Q[b]=a}var Ya={open:function(a){a.W=cb[a.node.wa].W;a.W.open&&a.W.open(a)},oa:function(){throw new O(70);}};function Ua(a,b){cb[a]={W:b}}
function tb(a,b){var c="/"===b,d=!b;if(c&&bb)throw new O(10);if(!c&&!d){var e=R(b,{Va:!1});b=e.path;e=e.node;if(e.Da)throw new O(10);if(16384!==(e.mode&61440))throw new O(54);}b={type:a,Cb:{},$a:b,sb:[]};a=a.ia(b);a.ia=b;b.root=a;c?bb=a:e&&(e.Da=b,e.ia&&e.ia.sb.push(b));return a}function ub(a,b,c){var d=R(a,{parent:!0}).node;a=Pa(a);if(!a||"."===a||".."===a)throw new O(28);var e=pb(d,a);if(e)throw new O(e);if(!d.Y.Ca)throw new O(63);return d.Y.Ca(d,a,b,c)}
function U(a,b){return ub(a,(void 0!==b?b:511)&1023|16384,0)}function vb(a,b,c){"undefined"===typeof c&&(c=b,b=438);ub(a,b|8192,c)}function wb(a,b){if(!Ra(a))throw new O(44);var c=R(b,{parent:!0}).node;if(!c)throw new O(44);b=Pa(b);var d=pb(c,b);if(d)throw new O(d);if(!c.Y.Fa)throw new O(63);c.Y.Fa(c,b,a)}function ib(a){a=R(a).node;if(!a)throw new O(44);if(!a.Y.xa)throw new O(28);return Ra(jb(a.parent),a.Y.xa(a))}
function xb(a,b,c,d){if(""===a)throw new O(44);if("string"===typeof b){var e=nb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=N(a);try{f=R(a,{Ia:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(f){if(b&128)throw new O(20);}else f=ub(a,c,0),e=!0;if(!f)throw new O(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new O(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==ob(b)||b&512)?31:lb(f,ob(b)):44))throw new O(c);if(b&512){c=f;c="string"===typeof c?R(c,{Ia:!0}).node:c;if(!c.Y.la)throw new O(63);if(16384===(c.mode&61440))throw new O(31);if(32768!==(c.mode&61440))throw new O(28);if(e=lb(c,"w"))throw new O(e);c.Y.la(c,{size:0,timestamp:Date.now()})}b&=-131713;d=rb({node:f,path:jb(f),flags:b,seekable:!0,position:0,W:f.W,yb:[],error:!1},d,void 0);d.W.open&&d.W.open(d);!g.logReadFiles||b&1||(yb||(yb={}),a in yb||(yb[a]=1,p("FS.trackingDelegate error on read file: "+
a)));try{hb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),hb.onOpenFile(a,f))}catch(k){p("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function zb(a,b,c){if(null===a.ea)throw new O(8);if(!a.seekable||!a.W.oa)throw new O(70);if(0!=c&&1!=c&&2!=c)throw new O(28);a.position=a.W.oa(a,b,c);a.yb=[]}
function Ab(a,b,c,d){var e=E;if(0>c||0>d)throw new O(28);if(null===a.ea)throw new O(8);if(0===(a.flags&2097155))throw new O(8);if(16384===(a.node.mode&61440))throw new O(31);if(!a.W.write)throw new O(28);a.seekable&&a.flags&1024&&zb(a,0,2);var f="undefined"!==typeof d;if(!f)d=a.position;else if(!a.seekable)throw new O(70);b=a.W.write(a,e,b,c,d,void 0);f||(a.position+=b);try{if(a.path&&hb.onWriteToFile)hb.onWriteToFile(a.path)}catch(k){p("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
k.message)}return b}function Bb(){O||(O=function(a,b){this.node=b;this.xb=function(c){this.$=c};this.xb(a);this.message="FS error"},O.prototype=Error(),O.prototype.constructor=O,[44].forEach(function(a){$a[a]=new O(a);$a[a].stack="<generic error, no stack>"}))}var Cb;function Db(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Eb(a,b,c){a=N("/dev/"+a);var d=Db(!!b,!!c);Fb||(Fb=64);var e=Fb++<<8|0;Ua(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,k,m,n){for(var q=0,u=0;u<n;u++){try{var t=b()}catch(z){throw new O(29);}if(void 0===t&&0===q)throw new O(6);if(null===t||void 0===t)break;q++;k[m+u]=t}q&&(f.node.timestamp=Date.now());return q},write:function(f,k,m,n){for(var q=0;q<n;q++)try{c(k[m+q])}catch(u){throw new O(29);}n&&(f.node.timestamp=Date.now());return q}});
vb(a,d,e)}var Fb,V={},sb,yb,Gb=void 0;function W(){Gb+=4;return I[Gb-4>>2]}function Hb(a){a=Q[a];if(!a)throw new O(8);return a}
var X={ia:function(){g.websocket=g.websocket&&"object"===typeof g.websocket?g.websocket:{};g.websocket.Ga={};g.websocket.on=function(a,b){"function"===typeof b&&(this.Ga[a]=b);return this};g.websocket.za=function(a,b){"function"===typeof this.Ga[a]&&this.Ga[a].call(this,b)};return Za(null,"/",16895,0)},mb:function(a,b,c){b&=-526337;c&&w(1==b==(6==c));a={family:a,type:b,protocol:c,ka:null,error:null,va:{},pending:[],ra:[],ga:X.fa};b=X.Ea();c=Za(X.root,b,49152,0);c.sa=a;b=rb({path:b,node:c,flags:2,
seekable:!1,W:X.W});a.stream=b;return a},pb:function(a){return(a=Q[a])&&49152===(a.node.mode&49152)?a.node.sa:null},W:{qa:function(a){a=a.node.sa;return a.ga.qa(a)},Ba:function(a,b,c){a=a.node.sa;return a.ga.Ba(a,b,c)},read:function(a,b,c,d){a=a.node.sa;d=a.ga.cb(a,d);if(!d)return 0;b.set(d.buffer,c);return d.buffer.length},write:function(a,b,c,d){a=a.node.sa;return a.ga.hb(a,b,c,d)},close:function(a){a=a.node.sa;a.ga.close(a)}},Ea:function(){X.Ea.current||(X.Ea.current=0);return"socket["+X.Ea.current++ +
"]"},fa:{Ta:function(a,b,c){if("object"===typeof b){var d=b;c=b=null}if(d)if(d.Pa)b=d.Pa.Eb,c=d.Pa.Fb;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e=g.websocket&&"object"===typeof g.websocket,f="ws:#".replace("#","//");e&&"string"===typeof g.websocket.url&&(f=g.websocket.url);if("ws://"===f||"wss://"===f){var k=b.split("/");f=f+k[0]+":"+c+"/"+k.slice(1).join("/")}k="binary";e&&"string"===
typeof g.websocket.subprotocol&&(k=g.websocket.subprotocol);var m=void 0;"null"!==k&&(m=k=k.replace(/^ +| +$/g,"").split(/ *, */));e&&null===g.websocket.subprotocol&&(m=void 0);d=new WebSocket(f,m);d.binaryType="arraybuffer"}catch(n){throw new O(23);}b={ca:b,port:c,X:d,ya:[]};X.fa.Qa(a,b);X.fa.rb(a,b);2===a.type&&"undefined"!==typeof a.ta&&b.ya.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.ta&65280)>>8,a.ta&255]));return b},Aa:function(a,b,c){return a.va[b+":"+c]},Qa:function(a,b){a.va[b.ca+
":"+b.port]=b},eb:function(a,b){delete a.va[b.ca+":"+b.port]},rb:function(a,b){var c=!0;b.X.onopen=function(){g.websocket.za("open",a.stream.ea);try{for(var d=b.ya.shift();d;)b.X.send(d),d=b.ya.shift()}catch(e){b.X.close()}};b.X.onclose=function(){g.websocket.za("close",a.stream.ea)};b.X.onmessage=function(d){a:{d=d.data;if("string"===typeof d)d=(new TextEncoder).encode(d);else{w(void 0!==d.byteLength);if(0==d.byteLength)break a;d=new Uint8Array(d)}var e=c;c=!1;e&&10===d.length&&255===d[0]&&255===
d[1]&&255===d[2]&&255===d[3]&&112===d[4]&&111===d[5]&&114===d[6]&&116===d[7]?(d=d[8]<<8|d[9],X.fa.eb(a,b),b.port=d,X.fa.Qa(a,b)):(a.ra.push({ca:b.ca,port:b.port,data:d}),g.websocket.za("message",a.stream.ea))}};b.X.onerror=function(){a.error=14;g.websocket.za("error",[a.stream.ea,a.error,"ECONNREFUSED: Connection refused"])}},qa:function(a){if(1===a.type&&a.ka)return a.pending.length?65:0;var b=0,c=1===a.type?X.fa.Aa(a,a.ma,a.na):null;if(a.ra.length||!c||c&&c.X.readyState===c.X.CLOSING||c&&c.X.readyState===
c.X.CLOSED)b|=65;if(!c||c&&c.X.readyState===c.X.OPEN)b|=4;if(c&&c.X.readyState===c.X.CLOSING||c&&c.X.readyState===c.X.CLOSED)b|=16;return b},Ba:function(a,b,c){switch(b){case 21531:return b=0,a.ra.length&&(b=a.ra[0].data.length),I[c>>2]=b,0;default:return 28}},close:function(a){if(a.ka){try{a.ka.close()}catch(e){}a.ka=null}for(var b=Object.keys(a.va),c=0;c<b.length;c++){var d=a.va[b[c]];try{d.X.close()}catch(e){}X.fa.eb(a,d)}return 0},bind:function(a,b,c){if("undefined"!==typeof a.Oa||"undefined"!==
typeof a.ta)throw new O(28);a.Oa=b;a.ta=c;if(2===a.type){a.ka&&(a.ka.close(),a.ka=null);try{a.ga.Ya(a,0)}catch(d){if(!(d instanceof O))throw d;if(138!==d.$)throw d;}}},connect:function(a,b,c){if(a.ka)throw new O(138);if("undefined"!==typeof a.ma&&"undefined"!==typeof a.na){var d=X.fa.Aa(a,a.ma,a.na);if(d){if(d.X.readyState===d.X.CONNECTING)throw new O(7);throw new O(30);}}b=X.fa.Ta(a,b,c);a.ma=b.ca;a.na=b.port;throw new O(26);},Ya:function(){throw new O(138);},accept:function(a){if(!a.ka)throw new O(28);
var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Bb:function(a,b){if(b){if(void 0===a.ma||void 0===a.na)throw new O(53);b=a.ma;a=a.na}else b=a.Oa||0,a=a.ta||0;return{ca:b,port:a}},hb:function(a,b,c,d,e,f){if(2===a.type){if(void 0===e||void 0===f)e=a.ma,f=a.na;if(void 0===e||void 0===f)throw new O(17);}else e=a.ma,f=a.na;var k=X.fa.Aa(a,e,f);if(1===a.type){if(!k||k.X.readyState===k.X.CLOSING||k.X.readyState===k.X.CLOSED)throw new O(53);if(k.X.readyState===k.X.CONNECTING)throw new O(6);
}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(2===a.type&&(!k||k.X.readyState!==k.X.OPEN))return k&&k.X.readyState!==k.X.CLOSING&&k.X.readyState!==k.X.CLOSED||(k=X.fa.Ta(a,e,f)),k.ya.push(b),d;try{return k.X.send(b),d}catch(m){throw new O(28);}},cb:function(a,b){if(1===a.type&&a.ka)throw new O(53);var c=a.ra.shift();if(!c){if(1===a.type){if(a=X.fa.Aa(a,a.ma,a.na)){if(a.X.readyState===a.X.CLOSING||a.X.readyState===a.X.CLOSED)return null;throw new O(6);}throw new O(53);}throw new O(6);
}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var k={buffer:new Uint8Array(f,e,b),ca:c.ca,port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.ra.unshift(c));return k}}};function Y(a){a=X.pb(a);if(!a)throw new O(8);return a}function Ib(a){return(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255)}
function Jb(a){var b="",c,d=0,e=0,f=0,k=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var m=!0;for(c=0;5>c;c++)if(0!==a[c]){m=!1;break}if(m){c=Ib(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-e&&(k=0),e=c,k++),k>d&&(d=k,f=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=f&&c<f+d?c===f&&(b+=":",0===f&&(b+=":")):(b+=Number(Kb(a[c]&65535)).toString(16),b+=7>c?":":"");return b}
function Lb(a,b){var c=H[a>>1],d=Kb(xa[a+2>>1]);switch(c){case 2:if(16!==b)return{$:28};a=I[a+4>>2];a=Ib(a);break;case 10:if(28!==b)return{$:28};a=[I[a+8>>2],I[a+12>>2],I[a+16>>2],I[a+20>>2]];a=Jb(a);break;default:return{$:5}}return{family:c,ca:a,port:d}}function Mb(a,b,c){if(c&&0===a)return null;a=Lb(a,b);if(a.$)throw new O(a.$);b=a.ca;a.ca=(Nb[b]?Nb[b]:null)||a.ca;return a}
function Ob(a){a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0}
function Pb(a){var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(/[.]/g,":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-
1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"===typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=Qb(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]}
function Rb(a,b,c,d,e){switch(b){case 2:c=Ob(c);B.fill(0,a,a+16);e&&(I[e>>2]=16);H[a>>1]=b;I[a+4>>2]=c;H[a+2>>1]=Qb(d);break;case 10:c=Pb(c);B.fill(0,a,a+28);e&&(I[e>>2]=28);I[a>>2]=b;I[a+8>>2]=c[0];I[a+12>>2]=c[1];I[a+16>>2]=c[2];I[a+20>>2]=c[3];H[a+2>>1]=Qb(d);break;default:return 5}return 0}var Sb=1,Tb={},Nb={};
function Ub(a){var b=Ob(a);if(null!==b)return a;b=Pb(a);if(null!==b)return a;Tb[a]?b=Tb[a]:(b=Sb++,w(65535>b,"exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),Nb[b]=a,Tb[a]=b);return b}var Vb;Vb=function(){return performance.now()};var Wb={};
function Xb(){if(!Yb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Wb)void 0===Wb[b]?delete a[b]:a[b]=Wb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Yb=c}return Yb}var Yb;function Zb(a){try{a()}catch(b){r(b)}}var Z=0,F=null,$b=0,ac=[],bc={},cc={},dc=0,ec=null,qa=[],fc=[];
function gc(a){var b={},c;for(c in a)(function(d){var e=a[d];b[d]="function"===typeof e?function(){ac.push(d);try{return e.apply(null,arguments)}finally{if(!v){var f=ac.pop();w(f===d);F&&1===Z&&0===ac.length&&(Z=0,Zb(g._asyncify_stop_unwind),"undefined"!==typeof Fibers&&Fibers.Gb(),ec&&(ec(),ec=null))}}}:e})(c);return b}function hc(){var a=G(4108),b=a+12;I[a>>2]=b;I[a+4>>2]=b+4096;b=ac[0];var c=bc[b];void 0===c&&(c=dc++,bc[b]=c,cc[c]=b);I[a+8>>2]=c;return a}
function ic(a){if(!v){if(0===Z){var b=!1,c=!1;a(function(d){if(!v&&($b=d||0,b=!0,c)){Z=2;Zb(function(){g._asyncify_start_rewind(F)});"undefined"!==typeof jc&&jc.La.Wa&&jc.La.resume();var e=(0,g.asm[cc[I[F+8>>2]]])();F||(d=qa,qa=[],d.forEach(function(f){f(e)}))}});c=!0;b||(Z=1,F=hc(),Zb(function(){g._asyncify_start_unwind(F)}),"undefined"!==typeof jc&&jc.La.Wa&&jc.La.pause())}else 2===Z?(Z=0,Zb(g._asyncify_stop_rewind),kc(F),F=null,fc.forEach(function(d){if(!v)try{d()}catch(e){if(!(e instanceof lc)&&
"unwind"!==e)throw e&&"object"===typeof e&&e.stack&&p("exception thrown: "+[e,e.stack]),e;}})):r("invalid state: "+Z);return $b}}function mc(a){return ic(function(b){a().then(b)})}var pa={};function mb(a,b,c,d){a||(a=this);this.parent=a;this.ia=a.ia;this.Da=null;this.id=db++;this.name=b;this.mode=c;this.Y={};this.W={};this.wa=d}
Object.defineProperties(mb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Bb();eb=Array(4096);tb(P,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");Ua(259,{read:function(){return 0},write:function(b,c,d,e){return e}});vb("/dev/null",259);Ta(1280,Wa);Ta(1536,Xa);vb("/dev/tty",1280);vb("/dev/tty1",1536);var a=Qa();Eb("random",a);Eb("urandom",a);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");tb({ia:function(){var b=Za(a,"fd",16895,73);b.Y={ua:function(c,d){var e=Q[+d];if(!e)throw new O(8);c={parent:null,ia:{$a:"fake"},Y:{xa:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();
var jc,pc={y:function(a,b,c,d){try{for(var e=0,f=b?I[b>>2]:0,k=b?I[b+4>>2]:0,m=c?I[c>>2]:0,n=c?I[c+4>>2]:0,q=d?I[d>>2]:0,u=d?I[d+4>>2]:0,t=0,z=0,D=0,S=0,x=0,T=0,ca=(b?I[b>>2]:0)|(c?I[c>>2]:0)|(d?I[d>>2]:0),rc=(b?I[b+4>>2]:0)|(c?I[c+4>>2]:0)|(d?I[d+4>>2]:0),C=0;C<a;C++){var A=1<<C%32;if(32>C?ca&A:rc&A){var Ba=Q[C];if(!Ba)throw new O(8);var Ca=5;Ba.W.qa&&(Ca=Ba.W.qa(Ba));Ca&1&&(32>C?f&A:k&A)&&(32>C?t|=A:z|=A,e++);Ca&4&&(32>C?m&A:n&A)&&(32>C?D|=A:S|=A,e++);Ca&2&&(32>C?q&A:u&A)&&(32>C?x|=A:T|=A,e++)}}b&&
(I[b>>2]=t,I[b+4>>2]=z);c&&(I[c>>2]=D,I[c+4>>2]=S);d&&(I[d>>2]=x,I[d+4>>2]=T);return e}catch(fb){return"undefined"!==typeof V&&fb instanceof O||r(fb),-fb.$}},r:function(a,b,c){try{var d=Y(a),e=Mb(b,c);d.ga.bind(d,e.ca,e.port);return 0}catch(f){return"undefined"!==typeof V&&f instanceof O||r(f),-f.$}},q:function(a,b,c){try{var d=Y(a),e=Mb(b,c);d.ga.connect(d,e.ca,e.port);return 0}catch(f){return"undefined"!==typeof V&&f instanceof O||r(f),-f.$}},b:function(a,b,c){Gb=c;try{var d=Hb(a);switch(b){case 0:var e=
W();return 0>e?-28:xb(d.path,d.flags,0,e).ea;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=W(),d.flags|=e,0;case 12:return e=W(),H[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return I[nc()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof V&&f instanceof O||r(f),-f.$}},w:function(a,b){try{if(0===b)return-28;if(b<ua("/")+1)return-68;na("/",B,a,b);return a}catch(c){return"undefined"!==typeof V&&c instanceof O||r(c),-c.$}},o:function(a,b,c){try{p("__sys_getsockname "+
a);var d=Y(a);Rb(b,d.family,Ub(d.Oa||"0.0.0.0"),d.ta,c);return 0}catch(e){return"undefined"!==typeof V&&e instanceof O||r(e),-e.$}},l:function(a,b,c,d,e){try{var f=Y(a);return 1===b&&4===c?(I[d>>2]=f.error,I[e>>2]=4,f.error=null,0):-50}catch(k){return"undefined"!==typeof V&&k instanceof O||r(k),-k.$}},B:function(a,b,c){Gb=c;try{var d=Hb(a);switch(b){case 21509:case 21505:return d.ba?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.ba?0:-59;case 21519:if(!d.ba)return-59;
var e=W();return I[e>>2]=0;case 21520:return d.ba?-28:-59;case 21531:a=e=W();if(!d.W.Ba)throw new O(59);return d.W.Ba(d,b,a);case 21523:return d.ba?0:-59;case 21524:return d.ba?0:-59;default:r("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof V&&f instanceof O||r(f),-f.$}},p:function(a,b){try{var c=Y(a);c.ga.Ya(c,b);return 0}catch(d){return"undefined"!==typeof V&&d instanceof O||r(d),-d.$}},i:function(a,b){try{return a=y(a),a=N(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),U(a,b),
0}catch(c){return"undefined"!==typeof V&&c instanceof O||r(c),-c.$}},j:function(a,b,c){Gb=c;try{var d=y(a),e=c?W():0;return xb(d,b,e).ea}catch(f){return"undefined"!==typeof V&&f instanceof O||r(f),-f.$}},x:function(a,b){try{for(var c=0,d=0;d<b;d++){var e=a+8*d,f=H[e+4>>1],k=32,m=Q[I[e>>2]];m&&(k=5,m.W.qa&&(k=m.W.qa(m)));(k&=f|24)&&c++;H[e+6>>1]=k}return c}catch(n){return"undefined"!==typeof V&&n instanceof O||r(n),-n.$}},m:function(a,b,c,d,e,f){try{var k=Y(a),m=k.ga.cb(k,c);if(!m)return 0;e&&Rb(e,
k.family,Ub(m.ca),m.port,f);B.set(m.buffer,b);return m.buffer.byteLength}catch(n){return"undefined"!==typeof V&&n instanceof O||r(n),-n.$}},n:function(a,b,c,d,e,f){try{var k=Y(a),m=Mb(e,f,!0);return m?k.ga.hb(k,E,b,c,m.ca,m.port):Ab(k.stream,b,c)}catch(n){return"undefined"!==typeof V&&n instanceof O||r(n),-n.$}},s:function(a,b,c){try{return X.mb(a,b,c).stream.ea}catch(d){return"undefined"!==typeof V&&d instanceof O||r(d),-d.$}},C:function(a,b){try{a=y(a);a:{try{var c=R(a,{Ia:!0}).node;if(!c)throw new O(44);
if(!c.Y.ha)throw new O(63);var d=c.Y.ha(c)}catch(f){if(f&&f.node&&N(a)!==N(jb(f.node))){var e=-54;break a}throw f;}I[b>>2]=d.ob;I[b+4>>2]=0;I[b+8>>2]=d.Ka;I[b+12>>2]=d.mode;I[b+16>>2]=d.vb;I[b+20>>2]=d.uid;I[b+24>>2]=d.qb;I[b+28>>2]=d.wa;I[b+32>>2]=0;M=[d.size>>>0,(L=d.size,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];I[b+40>>2]=M[0];I[b+44>>2]=M[1];I[b+48>>2]=4096;I[b+52>>2]=d.lb;I[b+56>>2]=d.jb.getTime()/1E3|0;I[b+60>>
2]=0;I[b+64>>2]=d.tb.getTime()/1E3|0;I[b+68>>2]=0;I[b+72>>2]=d.nb.getTime()/1E3|0;I[b+76>>2]=0;M=[d.Ka>>>0,(L=d.Ka,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];I[b+80>>2]=M[0];I[b+84>>2]=M[1];e=0}return e}catch(f){return"undefined"!==typeof V&&f instanceof O||r(f),-f.$}},c:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Vb();else return I[nc()>>2]=28,-1;I[b>>2]=a/1E3|0;I[b+4>>2]=a%1E3*1E6|0;return 0},f:function(a){var b=
B.length;a>>>=0;if(1073741824<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(1073741824,d)-wa.byteLength+65535>>>16);ya();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},u:function(a,b){try{var c=0;Xb().forEach(function(d,e){var f=b+c;e=I[a+4*e>>2]=f;for(f=0;f<d.length;++f)E[e++>>0]=d.charCodeAt(f);E[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof V&&d instanceof O||
r(d),d.$}},v:function(a,b){try{var c=Xb();I[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});I[b>>2]=d;return 0}catch(e){return"undefined"!==typeof V&&e instanceof O||r(e),e.$}},t:function(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);v=!0}fa(a,new lc(a))},a:function(a){try{var b=Hb(a);if(null===b.ea)throw new O(8);b.Ja&&(b.Ja=null);try{b.W.close&&b.W.close(b)}catch(c){throw c;}finally{Q[b.ea]=null}b.ea=null;return 0}catch(c){return"undefined"!==typeof V&&c instanceof O||r(c),c.$}},A:function(a,
b,c,d){try{a:{for(var e=Hb(a),f=a=0;f<c;f++){var k=I[b+(8*f+4)>>2],m=e,n=I[b+8*f>>2],q=k,u=void 0,t=E;if(0>q||0>u)throw new O(28);if(null===m.ea)throw new O(8);if(1===(m.flags&2097155))throw new O(8);if(16384===(m.node.mode&61440))throw new O(31);if(!m.W.read)throw new O(28);var z="undefined"!==typeof u;if(!z)u=m.position;else if(!m.seekable)throw new O(70);var D=m.W.read(m,t,n,q,u);z||(m.position+=D);var S=D;if(0>S){var x=-1;break a}a+=S;if(S<k)break}x=a}I[d>>2]=x;return 0}catch(T){return"undefined"!==
typeof V&&T instanceof O||r(T),T.$}},k:function(a,b,c,d,e){try{var f=Hb(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;zb(f,a,d);M=[f.position>>>0,(L=f.position,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];I[e>>2]=M[0];I[e+4>>2]=M[1];f.Ja&&0===a&&0===d&&(f.Ja=null);return 0}catch(k){return"undefined"!==typeof V&&k instanceof O||r(k),k.$}},z:function(a,b,c,d){try{a:{for(var e=Hb(a),f=a=0;f<
c;f++){var k=Ab(e,I[b+8*f>>2],I[b+(8*f+4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}I[d>>2]=m;return 0}catch(n){return"undefined"!==typeof V&&n instanceof O||r(n),n.$}},e:function(a,b,c,d){function e(t,z,D,S,x,T){var ca=10===t?28:16;x=10===t?Jb(x):Ib(x);ca=G(ca);x=Rb(ca,t,x,T);w(!x);x=G(32);I[x+4>>2]=t;I[x+8>>2]=z;I[x+12>>2]=D;I[x+24>>2]=S;I[x+20>>2]=ca;I[x+16>>2]=10===t?28:16;I[x+28>>2]=0;return x}var f=0,k=0,m=0,n=0,q=0,u=0;c&&(m=I[c>>2],n=I[c+4>>2],q=I[c+8>>2],u=I[c+12>>2]);q&&!u&&(u=2===q?
17:6);!q&&u&&(q=17===u?2:1);0===u&&(u=6);0===q&&(q=1);if(!a&&!b)return-2;if(m&-1088||0!==c&&I[c>>2]&2&&!a)return-1;if(m&32)return-2;if(0!==q&&1!==q&&2!==q)return-7;if(0!==n&&2!==n&&10!==n)return-6;if(b&&(b=y(b),k=parseInt(b,10),isNaN(k)))return m&1024?-2:-8;if(!a)return 0===n&&(n=2),0===(m&1)&&(2===n?f=oc(2130706433):f=[0,0,0,1]),a=e(n,q,u,null,f,k),I[d>>2]=a,0;a=y(a);f=Ob(a);if(null!==f)if(0===n||2===n)n=2;else if(10===n&&m&8)f=[0,0,oc(65535),f],n=10;else return-2;else if(f=Pb(a),null!==f)if(0===
n||10===n)n=10;else return-2;if(null!=f)return a=e(n,q,u,a,f,k),I[d>>2]=a,0;if(m&4)return-2;a=Ub(a);f=Ob(a);0===n?n=2:10===n&&(f=[0,0,oc(65535),f]);a=e(n,q,u,null,f,k);I[d>>2]=a;return 0},d:function(a){a=y(a);var b=G(20),c=G(a.length+1);na(a,B,c,a.length+1);I[b>>2]=c;c=G(4);I[c>>2]=0;I[b+4>>2]=c;I[b+8>>2]=2;I[b+12>>2]=4;c=G(12);I[c>>2]=c+8;I[c+4>>2]=0;I[c+8>>2]=Ob(Ub(a));I[b+16>>2]=c;return b},h:function(a){var b=Date.now()/1E3|0;a&&(I[a>>2]=b);return b},g:function(a){return mc(async()=>{const b=
y(a);try{const c=await fetch(b);if(200!=c.status)return null;const d=await c.text();return va(d)}catch(c){return null}})}};
(function(){function a(f){f=f.exports;f=gc(f);g.asm=f;ja=g.asm.D;ya();Aa.unshift(g.asm.E);J--;g.monitorRunDependencies&&g.monitorRunDependencies(J);0==J&&(null!==Fa&&(clearInterval(Fa),Fa=null),Ga&&(f=Ga,Ga=null,f()))}function b(f){a(f.instance)}function c(f){return Ka().then(function(k){return WebAssembly.instantiate(k,d)}).then(f,function(k){p("failed to asynchronously prepare wasm: "+k);r(k)})}var d={a:pc};J++;g.monitorRunDependencies&&g.monitorRunDependencies(J);if(g.instantiateWasm)try{var e=
g.instantiateWasm(d,a);return e=gc(e)}catch(f){return p("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return ia||"function"!==typeof WebAssembly.instantiateStreaming||Ha()||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(k){p("wasm streaming compile failed: "+k);p("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.E).apply(null,arguments)};g._xsltJsTransform=function(){return(g._xsltJsTransform=g.asm.F).apply(null,arguments)};g._xsltJsLastError=function(){return(g._xsltJsLastError=g.asm.G).apply(null,arguments)};
var nc=g.___errno_location=function(){return(nc=g.___errno_location=g.asm.H).apply(null,arguments)},G=g._malloc=function(){return(G=g._malloc=g.asm.I).apply(null,arguments)},kc=g._free=function(){return(kc=g._free=g.asm.J).apply(null,arguments)},Qb=g._htons=function(){return(Qb=g._htons=g.asm.K).apply(null,arguments)},Kb=g._ntohs=function(){return(Kb=g._ntohs=g.asm.L).apply(null,arguments)},oc=g._htonl=function(){return(oc=g._htonl=g.asm.M).apply(null,arguments)},oa=g.stackSave=function(){return(oa=
g.stackSave=g.asm.N).apply(null,arguments)},ra=g.stackRestore=function(){return(ra=g.stackRestore=g.asm.O).apply(null,arguments)},ma=g.stackAlloc=function(){return(ma=g.stackAlloc=g.asm.P).apply(null,arguments)},Ma=g.dynCall_vi=function(){return(Ma=g.dynCall_vi=g.asm.R).apply(null,arguments)};g._asyncify_start_unwind=function(){return(g._asyncify_start_unwind=g.asm.S).apply(null,arguments)};g._asyncify_stop_unwind=function(){return(g._asyncify_stop_unwind=g.asm.T).apply(null,arguments)};
g._asyncify_start_rewind=function(){return(g._asyncify_start_rewind=g.asm.U).apply(null,arguments)};g._asyncify_stop_rewind=function(){return(g._asyncify_stop_rewind=g.asm.V).apply(null,arguments)};g.ccall=la;g.cwrap=function(a,b,c,d){c=c||[];var e=c.every(function(f){return"number"===f});return"string"!==b&&e&&!d?ka(a):function(){return la(a,b,c,arguments,d)}};g.UTF8ToString=y;g.allocateUTF8=va;var qc;
function lc(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ga=function sc(){qc||tc();qc||(Ga=sc)};
function tc(){function a(){if(!qc&&(qc=!0,g.calledRun=!0,!v)){g.noFSInit||Cb||(Cb=!0,Bb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Eb("stdin",g.stdin):wb("/dev/tty","/dev/stdin"),g.stdout?Eb("stdout",null,g.stdout):wb("/dev/tty","/dev/stdout"),g.stderr?Eb("stderr",null,g.stderr):wb("/dev/tty1","/dev/stderr"),xb("/dev/stdin",0),xb("/dev/stdout",1),xb("/dev/stderr",1));gb=!1;X.root=tb(X,null);La(Aa);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Da.unshift(b)}La(Da)}}if(!(0<J)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ea();La(za);0<J||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=tc;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();tc();


  return createXsltModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createXsltModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createXsltModule; });
else if (typeof exports === 'object')
  exports["createXsltModule"] = createXsltModule;

  return async () => {
    const mod = await createXsltModule();
    return new XsltEngine(mod);
  };
})();
